### ISSUE TITLE
Action fails without the projectfilter-config parameter defined

### ISSUE THREAD

**Issue by evanwarner** [Matticusau/projectcard-autolabel#5]
## Bug Report

**Current Behavior**
Your example documentation omits `projectfilter-config` from the config and does not mark it as required, which made me assume the default was to include all projects. But the action fails with "Error: Unexpected end of JSON input" without it.

**To Reproduce**

1. Configure the action step without the `projectfilter-config` parameter.

**Expected behavior/code**
I expected that the action would process a card move in any project.

**GitHub Action Configuration (.yml, etc)**

```yaml
name: Auto Card Label
on:
  project_card:
    types: [moved]
jobs:
  label_card:
    runs-on: ubuntu-latest
    steps:
      - name: Run ProjectCard AutoLabel
        id: runprojectcardautolabel
        uses: Matticusau/projectcard-autolabel@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          autolabel-config: '[{"column":"In progress", "add_labels":["in progress"]}]'
```

**Possible Solution**
Adding `projectfilter-config: '{"include":["*"], "exclude":[]}'` in my config allows the action to run as expected.
