### ISSUE TITLE
I've done all right but the action doesn't trigger

### ISSUE THREAD

**Issue by ruiaraujo012** [Matticusau/projectcard-autolabel#6]
## I've done all right but the action doesn't trigger

**What is your question?**
My action doesn't trigger, I have followed all the readme but nothing happens.

**Background information**
```yml
name: Project Auto Label issue

on:
  project_card:
    types: [moved]

jobs:
  projectcardautolabel_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run ProjectCard AutoLabel
      id: runprojectcardautolabel
      uses: Matticusau/projectcard-autolabel@v1.0.0
      with:
        repo-token: ${{ secrets.GH_TOKEN }}
        autolabel-config: '[{"column":"In progress 🚧", "add_labels":["in progress"]}, {"column":"Ready 🏁", "add_labels":["ready"], "remove_labels":["in progress"]}, {"column":"Deployed 🚀", "remove_labels":["ready"]}]'
```

If it helps you, my project is an org project.
